@startuml

title Classes - Hospital Patient Archive Management

abstract User {
  - Int UserID
  - string name
  - string Password 
  - string email
  - string address
  - string phoneNumber
  - string CIN
}
enum Gender{
  F
  M
}
class Doctor {
  searchPatient()
  UpdatePatient()
}

class Nurse {
  searchPatient()
  UpdatePatient()
  createPatient()
  addAppointments()
  cancelAppointments()
  verifyInsurance()
}

User <|-- Doctor 
User <|-- Nurse
User <|-- Administrator

class Administrator {
  createDoctor()
  createNurse()
  deleteDoctor()
  deleteNurse()
}

class Patient {
  - int patientID
  - strind CIN
  - datetime birthDate
  - string firstName
  - string lastName
  - string insuranceInfo
  - string address
  - string phoneNumber
  - string email
  - string emergencyContact
  - BloodGroup bloodGroup
  - string allergies
  - string emergencyContactName
  - string emergencyContactPhone
  - string emergencyContactEmail
  - string emergencyContactAddress
  - string emergencyContactRelation
  - BloodGroup emergencyContactBloodGroup
}
enum BloodGroup {
  A+
  A-
  B+
  B-
  AB+
  AB-
  O+
  O-
}
class Appointment {
  -int appointmentId
  -datetime appointmentDate
  -status appointmentStatus
}

enum status {
  confirmed
  canceled
}

class MedicalRecord {
  - int recordId
  - datetime dateCreated
  - string treatmentPlan
  - string testResults
  - blob imageData
}

MedicalRecord "0..*" - "1" Nurse
Patient "1" - "0..*" Appointment
Patient "1" o-- "0..*" MedicalRecord
Appointment "0..*" - "1" Nurse
MedicalRecord "0..*" - "1" Doctor
Appointment "0..*" - "1" Doctor

@enduml
